-- database :
-- test

-- DROP DATABASE IF EXISTS PRIVASTREET;

-- CREATE DATABASE IF NOT EXISTS PRIVASTREET DEFAULT CHARSET UTF8 DEFAULT COLLATE UTF8_GENERAL_CI;

-- GRANT USAGE ON PRIVASTREET.* TO PRIVA_USER@localhost IDENTIFIED BY 'priva123';

-- GRANT SELECT, INSERT, UPDATE ON PRIVASTREET.* TO PRIVA_USER@localhost;

use PRIVASTREET;

-- t_USER Table structure
DROP TABLE IF EXISTS t_USER;

CREATE TABLE t_USER(
	ID_USER        INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	FIRST_NAME     VARCHAR(50)  NOT NULL,
	LAST_NAME      VARCHAR(50)  NOT NULL,
	MAIL           VARCHAR(50)  NOT NULL,
	PSEUDO         VARCHAR(50)  NOT NULL,
	PASSWORD       VARCHAR(255) NOT NULL,
	COUNTRY        VARCHAR(50),
	IS_ADMIN       TINYINT(1),
	ACTIVE         VARCHAR(255),
	RESET_TOKEN    VARCHAR(255),
	LAST_CONNEXION DATETIME,
	LAST_ACTIVITY  DATETIME,
	DATE_CREATION  DATETIME,
	UPDATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	IPADRESS	   VARCHAR(50),
	PRIMARY KEY (ID_USER),
	UNIQUE KEY uk_MAIL   (MAIL),
	UNIQUE KEY uk_PSEUDO (PSEUDO)
) ENGINE=InnoDB;


-- t_NEWS Table structure
DROP TABLE IF EXISTS t_NEWS;

CREATE TABLE t_NEWS(
	ID_NEWS        INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	ID_AUTHOR      INT(11) UNSIGNED NOT NULL,
	TITLE          VARCHAR(50) NOT NULL,
	DESCRIPTION    TEXT NOT NULL,
	CONTENT        TEXT NOT NULL,
	IMAGE          LONGBLOB,
	DATE_CREATION  DATETIME,
	DATE_UPDATE    DATETIME,
	UPDATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID_NEWS)
) ENGINE=InnoDB;


-- t_COMMENT Table structure
DROP TABLE IF EXISTS t_COMMENT;

CREATE TABLE t_COMMENT(
	ID_COMMENT     INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	ID_NEWS        INT(11) UNSIGNED NOT NULL,
	ID_AUTHOR      INT(11) UNSIGNED NOT NULL,
	CONTENT        TEXT NOT NULL,
	DATE_CREATION  DATETIME,
	UPDATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID_COMMENT)
) ENGINE=InnoDB;

